/*

 MYTILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : myTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MyTileMapWidth 32
#define MyTileMapHeight 18
#define MyTileMapBank 0

extern unsigned char MyTileMap[];

/* End of MYTILEMAP.H */
